CREATE TABLE TBL_TEST (
  ID VARCHAR2(20),
  PWD VARCHAR2(30)
);

-- WITH ADMIN OPTION
GRANT CREATE SESSION TO EMPLOYEE;

-- 객체 권한
-- 내 소유의 테이블이 아니면 사용자명 명시해야함
-- 생략하면 자동으로 본인..
SELECT *FROM EMPLOYEE.EMPLOYEE;

-- WITH GRANT OPTION
GRANT SELECT ON EMPLOYEE.EMPLOYEE TO HOMEWORK;

